# ==================================
#  Mosaic
# ==================================
'mosaicml/mpt-7b-8k-chat':
    model: 'mosaicml/mpt-7b-8k-chat'
    openai_api_key: 'EMPTY'
    openai_api_base: 'http://localhost:8000/v1'
    max_tokens: 1024
    temperature: 0.2
    model_kwargs:
        frequency_penalty: 1.0
        eos_token_id: 0
        pad_token_id: 0
        stop: '###'


# ==================================
#  GPT-based
# ==================================
'gpt-4-1106-preview':
    model_name: 'gpt-4-1106-preview'
    temperature: 0.2

'gpt-4-32k-0613':
    model_name: 'gpt-4-32k-0613'
    temperature: 0.2

'gpt-3.5-turbo':
    model_name: 'gpt-3.5-turbo'
    temperature: 0.2
